### ISSUE TITLE
Unhandled CHANGE_ENTITY due to missing card id

### ISSUE THREAD

**Issue by beheh** [HearthSim/python-hslog#6]
Looks like we're losing track of some card id. This seems to only affect Monster Hunter games where Toki, or the final boss Toki is in play.

https://sentry.io/hearthsim/hsreplaynet-lambdas/issues/537416952

**Comment by amw2104** [comment]
This only effects Monster Hunt currently. Let's time box this issue to 6 hours.

**Comment by jleclanche** [comment]
Here's what was happening:

GAME_RESET was added in Witchwood (Toki, monster hunt). This resets to an empty game state and was implemented in the previous version of the library.
If there are entities removed and re-created after the reset, these entities retain the same IDs. Now to prevent multiple entities with the same ID being added to the state tracker, I added safeguards in the previous version of python hearthstone, which check to ensure the entity doesn't already exist.

Now as of the latest patch, there are sometimes jumps in entity IDs, which prevented those safeguards from working. So I changed the entity tracking to be dict-based. That had been on the TODO for a while (ever since dicts were officially blessed as sorted). So we gain a bit of performance and sanity there, and the issue won't resurface. I also added a test for this behaviour.
